server:
  port: 8001

application:
  service.defs: @service.def@
  plugin.initializer: @plugin.initializer@

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wae?useSSL=false
    username: root
    password: W@3-Dr3@ming
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

jwt.config:
  tokenExpiredTime: 60
  refreshTokenExpiredTime: 60
  tokenIssuer: https://github.com/ntdatjoker
  tokenSigningKey: $2a$06$NKaevdMxo/hRD0vWeOKcsODY0AMHeWApFqaViUql481FzeYjKkCy6
  tokenHeaderPrefix: Bearer
